services:
  nextjs:
    image: souravdebanth/vacuumcare-frontend:latest

    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL
        - NEXT_PUBLIC_BASE_URL
    container_name: vacuum-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
